/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FolderItem: typeof import('./../components/FolderItem.vue')['default']
    FolderSelect: typeof import('./../components/FolderSelect.vue')['default']
    FolderTree: typeof import('./../components/FolderTree.vue')['default']
    MuyaEditor: typeof import('./../components/MuyaEditor.vue')['default']
    NoteItem: typeof import('./../components/NoteItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VditorEditor: typeof import('./../components/VditorEditor.vue')['default']
  }
}
